### ISSUE TITLE
react-native run-android fails

### ISSUE THREAD

**Issue by jojo05** [grigio/HAgnostic-News#1]
Where do I set the property MYAPP_RELEASE_STORE_FILE ?

**Comment by grigio** [comment]
Hi, you have generate yours. Here is the doc http://facebook.github.io/react-native/releases/0.20/docs/signed-apk-android.html and here is where to put it https://github.com/grigio/HAgnostic-News/blob/master/.gitignore#L15

**Comment by jojo05** [comment]
Thanks for the prompt answer
Is there a way to override the apk signing step ? 

I just want to check the app with react-native run-android

**Comment by grigio** [comment]
I didn't find it, feel free to reopen or send a PR if you find it

**Comment by jojo05** [comment]
I commented out the signingConfigs and it works!

For some reason, the debug build checks the signingConfigs, which is only for the release build. I imagine the issue is that the signingConfigs should be nested differently so that it is only check for a release build.

Thanks

**Comment by grigio** [comment]
@lu-zero Hi, these are the lines:
https://github.com/grigio/HAgnostic-News/blob/4e21e7176bc71de72fbde95e741ad9028d49cb51/android/app/build.gradle#L99-L106

Is possible to run the code in development mode without having to comment that lines, and without generating the signed-key ? (it is only required for the Play Store pubblication, not for the development on the personal device). Thanks

**Comment by lu-zero** [comment]
As explained [here](http://stackoverflow.com/questions/20562189/sign-apk-without-putting-keystore-info-in-build-gradle) you can keep a properties file off git and you can add another `buildType` that does not require a signingConfig.

**Comment by grigio** [comment]
@lu-zero Grazie, it seems the "optional" way I was looking for

**Comment by kenpeter** [comment]
I "clone" the project here: https://github.com/kenpeter/my_hak_news. Run react-native run-android. I still have `com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.hagnosticnews signatures do not match the previously installed version; ignoring!`

**Comment by mayupat13** [comment]
i have same problem what to do for it?

**Comment by grigio** [comment]
it should work via Expo
