### ISSUE TITLE
Failed to compile. (npm start)

### ISSUE THREAD

**Issue by kenpeter** [grigio/HAgnostic-News#2]
Related to this: https://codedump.io/share/JVC44fmZDwQC/1/error-in-react-tap-event-pluginsrcinjecttapeventpluginjs, I think

Failed to compile in my machine.

Error in ./~/react-native-web/dist/modules/injectResponderEventPlugin.js
Module not found: 'react/lib/EventConstants' in /var/www/html/test/testme/hak_news/node_modules/react-native-web/dist/modules

 @ ./~/react-native-web/dist/modules/injectResponderEventPlugin.js 1:20-55

Error in ./~/react-native-web/dist/modules/injectResponderEventPlugin.js
Module not found: 'react/lib/EventPluginRegistry' in /var/www/html/test/testme/hak_news/node_modules/react-native-web/dist/modules

 @ ./~/react-native-web/dist/modules/injectResponderEventPlugin.js 4:25-65

Error in ./~/react-native-web/dist/modules/injectResponderEventPlugin.js
Module not found: 'react/lib/ResponderEventPlugin' in /var/www/html/test/testme/hak_news/node_modules/react-native-web/dist/modules

 @ ./~/react-native-web/dist/modules/injectResponderEventPlugin.js 5:26-67

Error in ./~/react-native-web/dist/modules/injectResponderEventPlugin.js
Module not found: 'react/lib/ResponderTouchHistoryStore' in /var/www/html/test/testme/hak_news/node_modules/react-native-web/dist/modules

 @ ./~/react-native-web/dist/modules/injectResponderEventPlugin.js 6:32-79

Error in ./~/react-native-web/dist/apis/PanResponder/index.js
Module not found: 'react/lib/TouchHistoryMath' in /var/www/html/test/testme/hak_news/node_modules/react-native-web/dist/apis/PanResponder

 @ ./~/react-native-web/dist/apis/PanResponder/index.js 9:21-58

Error in ./~/react-native-web/dist/apis/UIManager/index.js
Module not found: 'react/lib/CSSPropertyOperations' in /var/www/html/test/testme/hak_news/node_modules/react-native-web/dist/apis/UIManager

 @ ./~/react-native-web/dist/apis/UIManager/index.js 2:27-69

**Comment by grigio** [comment]
maybe outdated deps? I'll look at it, thanks

**Comment by grigio** [comment]
@kenpeter it seems React Native has problems with old projects, I've updated the dependencies as much as possible. Try to:

```
git pull
rm -rfv node_modules
yarn # instead of npm
yarn run start
```

**Comment by kenpeter** [comment]
Ok, I reinstall everything with npm install xxx --save, now seems working. It is deps problem. Haven't tried yarn.

**Comment by grigio** [comment]
Ok, thanks. I close this for now
